import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { ROOT, loadContent, validateLinks } from './content.mjs';

const check = process.argv.includes('--check');
const { outline, topics, objectives, questions } = await loadContent();
const coverage = new Map(objectives.map(o => [o.id, topics.filter(t => t.objectives.includes(o.id))]));
const covered = [...coverage.values()].filter(ts => ts.length).length;
const generated = new Map();
const banner = '<!-- Generated by pnpm run build. Do not edit directly. -->\n\n';

let matrix = `${banner}# Objective coverage\n\nOutline: ${outline.outlineEffective}. Source checked: ${outline.verified}.\n\n`;
matrix += `${covered}/${objectives.length} objectives have documented topic coverage. This measures presence of researched content, not mastery or exhaustive scenario coverage.\n\n`;
matrix += `[Microsoft scope source](${outline.source}). IDs below are local identifiers.\n\n`;
for (const domain of outline.domains) {
  matrix += `## ${domain.title} (${domain.weight.join('–')}%)\n\n`;
  for (const group of domain.groups) {
    matrix += `### ${group.title}\n\n| ID | Task | Knowledge | Questions | Status |\n| --- | --- | --- | --- | --- |\n`;
    for (const o of group.objectives) {
      const ts = coverage.get(o.id);
      const count = questions.filter(q => q.objectives.includes(o.id)).length;
      matrix += `| ${o.id} | ${o.title} | ${ts.map(t => `[${t.title}](../${t.path})`).join(', ') || '—'} | ${count} | ${ts.length ? 'Documented; not lab-tested' : 'Planned'} |\n`;
    }
    matrix += '\n';
  }
}
generated.set('exam/coverage.md', matrix);

let questionnaire = `${banner}# AZ-104 practice questions\n\nSelect the stated number of answers. Multiple-answer questions use exact-match scoring. This printable list includes variants; the app selects only one per family per quiz.\n\n[Answer key](answers.md)\n\n`;
let answers = `${banner}# AZ-104 answer explanations\n\n[Questions without answers](questions.md)\n\n`;
for (const q of questions) {
  const topic = topics.find(t => t.id === q.topic);
  const domain = outline.domains.find(d => d.id === topic.domain);
  const heading = `## ${q.id}\n\nTopic: ${domain.title} › ${topic.title}.\n\n${q.prompt}\n\nSelect **${q.select}**. Difficulty: ${q.difficulty}.\n\n`;
  questionnaire += heading + q.options.map((o, i) => `${String.fromCharCode(65 + i)}. ${o.text}`).join('\n') + '\n\n';
  answers += heading;
  answers += q.options.map((o, i) => `- **${String.fromCharCode(65 + i)}. ${q.correct.includes(o.id) ? 'Correct' : 'Incorrect'}:** ${o.text} ${o.explanation}`).join('\n') + '\n\n';
  answers += `Study: [knowledge file](../${q.knowledge}). Evidence checked: ${q.verified}.\n\n`;
  answers += q.sources.map((source, i) => `[Microsoft source ${i + 1}](${source})`).join(' · ') + '\n\n';
}
generated.set('generated/questions.md', questionnaire);
generated.set('generated/answers.md', answers);
generated.set('app/data.json', JSON.stringify({ schemaVersion: 1, outlineEffective: outline.outlineEffective,
  coverage: { covered, total: objectives.length },
  domains: outline.domains.map(({ id, title, weight }) => ({ id, title, weight })), topics, questions }, null, 2) + '\n');

for (const [name, rawContent] of generated) {
  const content = rawContent.trimEnd() + '\n';
  const file = path.join(ROOT, name);
  if (check) {
    let current = '';
    try { current = await readFile(file, 'utf8'); } catch { /* Report missing output as stale. */ }
    if (current !== content) throw new Error(`${name} is missing or stale; run pnpm run build.`);
  } else {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, content);
  }
}
await validateLinks();
console.log(`${check ? 'Checked' : 'Built'} ${questions.length} questions, ${topics.length} topics; coverage ${covered}/${objectives.length}. Internal links checked.`);
